apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kushal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/kushalsamota/nginx:1.14.2
